### ISSUE TITLE
Installing from Artifactory seems stuck at version 2.37.1

### ISSUE THREAD

**Issue by larsskj** [jenkinsci/jfrog-plugin#32]
### Describe the bug

We have setup the JFrog plugin to install the latest version of the `jf` CLI from our Artifactory SaaS instance - just as described in the plugin documentation: A generic repo connected to JFrog - which shows 'Remote Artifactory detected' - and the tools setup in Jenkins points to this repo and the version field is empty - which should mean latest version.

### Current behavior

For some reason, Artifactory doesn't update the CLI client: The version found at `<reponame>/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf` is stuck at `2.37.1`. This is causing issues as the JFrog platform is being upgraded.

### Reproduction steps

Download the RELEASE artifact from the above path: It invariably delivers `2.37.1`.

### Expected behavior

We would expect to get the latest version as per documentation.

### JFrog plugin version

1.5.0

### JFrog CLI version

2.37.1 :-)

### Operating system type and version

Linux / Windows / Docker / Podman / Kubernetes

### JFrog Artifactory version

Latest SaaS

### JFrog Xray version

Latest SaaS

**Comment by yahavi** [comment]
@larsskj 
Thank you for reporting this issue. 

To resolve it, please uncheck the `Store Artifacts Locally` option in the remote repository configuration:
![image](https://github.com/jenkinsci/jfrog-plugin/assets/11367982/32a2198b-daa1-4e7d-b6e8-8ad9b69e6c0b)

Please let me know if that helped and we will add it to the documentation.

**Comment by larsskj** [comment]
Hi @yahavi ,

You're right - that did the trick: We do get the latest version now. It would probably be a good idea to update documentation. :-)

Thank you for solving this.
