### ISSUE TITLE
Remove "--password-stdin" from command sent by the plugin

### ISSUE THREAD

**Issue by Steelhammer** [jenkinsci/jfrog-plugin#42]
### How can we help?

Hi,

After updating to version 1.5.3, the command sent by the plugin includes "--password-stdin" which makes the command fail in my pipeline. Can I configure this?
1.5.3
`jf c add NNN --user=nnnnnnn --password-stdin --url=nnnnnn --artifactory-url=nnnnnn --distribution-url=nnnnnn --xray-url=nnnnnn --interactive=false --overwrite=true`
1.5.1
`jf c add NNN --user=nnnnnn ******** --url=nnnnnn --artifactory-url=nnnnnn --distribution-url=nnnnnn --xray-url=nnnnnn --interactive=false --overwrite=true`

Thanks

**Comment by rubroboletus** [comment]
Same here, with version 1.5.3 our pipeline is stuck on mentioned command.

**Comment by snup67** [comment]
The problem exist also on version **1.5.2**.
When I upgrade jfrog plugin to version **1.5.2** it got the same problem with --password-stdin,
When I upgrade jfrog plugin to version **1.5.3** I faced the same problem with --password-stdin,
for now I stay on jfrog **1.5.1** that working fine.

**Comment by rainerfrey-inxmail** [comment]
Different angle: 1.5.3 logs the jfrog-cli version, and I noticed my failing build used `2.34.6`. I have a single global tool definition, using "Install from Artifactory" and empty Version (should be latest). I defined explicit version of 2.70.0, and the command does not cause an error. (I wanted to say it works, but my build now hangs without any output for at least 15 minutes now - that seems like I ran into a different problem)

**Comment by animaldna** [comment]
I think this might need a bug label. 1.53 and 1.54 hang until timeout on `jf c add`. I didn't test on 1.52 based on the comment above, but 1.51 works fine. Version made no in my case difference.

**Comment by snup67** [comment]
Related to my first message, 
I'm using Jenkins on Kubernetes platform and using jfrog image as pod for Jenkins-slave so  I agree with **animaldna** ,
**this is a bug and should mark as bug label**

**Comment by jamieoneill** [comment]
same issue.
it was introduced here https://github.com/jenkinsci/jfrog-plugin/commit/6f34090349bc9e05560e95cdc57f21743f3bb79d

@EyalDelarea please address or provide what indented solution should be.

**Comment by yahavi** [comment]
@animaldna @Steelhammer @jamieoneill @rubroboletus @rainerfrey-inxmail 
Thank you for bringing this issue to our attention.  
The Jenkins JFrog plugin version 1.5.5 has been released, and it includes a rollback of https://github.com/jfrog/jenkins-jfrog-plugin/pull/101.
You're welcome to upgrade to this version, and we'd love to hear your feedback!

**Comment by jamieoneill** [comment]
thanks @yahavi for quick turn around.
