### ISSUE TITLE
Better release documentation

### ISSUE THREAD

**Issue by jamieoneill** [jenkinsci/jfrog-plugin#43]
### Is your feature request related to a problem? Please describe.

Can we have better documentation of changes in each release?
the [tag message](https://github.com/jenkinsci/jfrog-plugin/releases/tag/jfrog-1.5.5) provides no insight.
nor does the [jenkins plugin page](https://plugins.jenkins.io/jfrog/releases/).
digging through commits is not the ideal way to see what has changed.

As highlighted by https://github.com/jenkinsci/jfrog-plugin/issues/42 users may not want to upgrade based on what is featured in the release but have no way of knowing easily.

### Describe the solution you'd like to see

other plugins do a much better job at describing what has change between each release.
[ansicolor](https://plugins.jenkins.io/ansicolor/releases/) and [ant](https://plugins.jenkins.io/ant/releases/), just for example, provide way more detailed release notes.

**Comment by yahavi** [comment]
@jamieoneill  
Thank you for using the Jenkins JFrog plugin!  
You can find the release notes in the official GitHub repository: https://github.com/jfrog/jenkins-jfrog-plugin. For version 1.5.5, visit the specific release notes here: https://github.com/jfrog/jenkins-jfrog-plugin/releases/tag/jfrog-1.5.5.

**Comment by jamieoneill** [comment]
Sorry. Didn't realize they were two separate repositories.
