### ISSUE TITLE
add BuildInfoBadgeStep

### ISSUE THREAD

**Issue by donhui** [jenkinsci/jfrog-plugin#8]
### Is your feature request related to a problem? Please describe.

I noticed that [artifactory plugin](https://github.com/jfrog/jenkins-artifactory-plugin)  can provide a build bagde, that we can click the link to jump to jfrog to view the specific build info.
I think this function is very useful and I really like it.
But in reality, we use jfrog cli to build, collect build info, publish build info.
So I hope that there is an independent step to add the build info badge.

### Describe the solution you'd like to see

Add a BuildInfoBadgeStep.

**Comment by yahavi** [comment]
Thank you, @donhui, for using the Jenkins JFrog plugin!
We are pleased to inform you that we have included this feature in the most recent release, version 1.4.0.
You can expect this version to be available in the Jenkins Plugins manager soon.

Feel free to upgrade at your convenience, and we would greatly appreciate any feedback you may have on the new release.
